config/routes.rb
Rails.application.routes.draw do
  if ENV['MAINTENANCE'] == '1'
    root 'misc#maintenance'
    match '*path' => 'misc#maintenance', via: :all
  else
    root 'home#new'
    get 'start', to: 'home#start', as: 'start'
  end

  namespace :api, {format: 'json'} do
    namespace :v1 do
      Search::API_V1_NAMES.each { |menu| get "#{menu}/summary", to: "#{menu}#summary" }
      Search::API_V1_NAMES.each { |menu| get "#{menu}/list", to: "#{menu}#list" }
      get "summary/summary", to: "summary#summary"

      post 'users/update_instance_id', to: 'users#update_instance_id'
      post 'users/update_device_token', to: 'users#update_device_token'
      post 'periodic_report_settings', to: 'periodic_report_settings#update'
    end
  end

  get 'delete_tweets', to: 'delete_tweets#new'
  get 'delete_tweets/mypage', to: 'delete_tweets#show', as: :delete_tweets_mypage
  post "delete_tweets", to: "delete_tweets#delete"

  delete "reset_egotter", to: "reset_egotter#reset"
  post "reset_cache", to: "reset_cache#reset"

  namespace :directory do
    get "profiles(/:id1(/:id2))", to: "profiles#show", as: :profile
    get "timelines(/:id1(/:id2))", to: "timelines#show", as: :timeline
  end

  %i(maintenance privacy_policy terms_of_service specified_commercial_transactions support).each do |name|
    get name, to: "misc##{name}", as: name
  end
  get '/menu', to: redirect('/settings?via=routing_menu')

  %i(
    profiles
    friends
    followers
    statuses
    audience_insights
    close_friends
    favorite_friends
    scores
    usage_stats
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    resources controller_name, only: %i(show), param: :screen_name
  end

  get 'profiles/:screen_name/latest', to: 'profiles#latest', as: 'latest_profile'

  %i(
    friends
    followers
    close_friends
    favorite_friends
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    get "#{controller_name}/:screen_name/all", to: "#{controller_name}#all", as: "all_#{controller_name}"
  end
  match 'statuses/:screen_name/oembed' => proc { [404, {'Content-Type' => 'text/plain'}, ''] }, via: :get

  get 'one_sided_friends', to: 'one_sided_friends#new', as: :one_sided_friends_top
  get 'unfriends', to: 'unfriends#new', as: :unfriends_top
  get 'inactive_friends', to: 'inactive_friends#new', as: :inactive_friends_top
  get 'friends', to: 'friends#new', as: :friends_top
  get 'conversations', to: redirect('/')
  get 'relationships', to: redirect('/')

  resources :clusters, only: %i(create show), param: :screen_name
  get 'clusters', to: 'clusters#new', as: :clusters_top

  get '/searches/:screen_name/favoriting', to: redirect('/favorite_friends/%{screen_name}')
  %i(
      close_friends
      usage_stats
      inactive_friends
      friends
      followers
      blocking_or_blocked
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu}/%{screen_name}") }
  get '/searches/:screen_name/inactive_followers', to: redirect('/inactive_friends/%{screen_name}')
  %w(
      new_friends
      new_followers
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu.remove('new_')}/%{screen_name}") }
  get '/searches/:screen_name/clusters_belong_to', to: redirect('/clusters/%{screen_name}')

  resources :searches, only: %i(create), param: :screen_name
  get '/searches/:screen_name', to: redirect('/timelines/%{screen_name}')
  get 'searches/:uid/waiting', to: redirect('/waiting/%{uid}')
  get 'waiting/:uid', to: 'waiting#new', as: :waiting

  resources :account_statuses, only: %i(show), param: :uid
  resources :twitter_users, only: %i(create show), param: :uid
  get 'twitter_users/:uid/changes', to: 'twitter_users#changes', as: :twitter_users_changes

  resources :timelines, only: %i(show), param: :screen_name

  resources :not_found, only: %i(show), param: :screen_name
  get 'not_found/:screen_name/latest', to: 'not_found#latest', as: 'latest_not_found'
  resources :forbidden, only: %i(show), param: :screen_name
  get 'forbidden/:screen_name/latest', to: 'forbidden#latest', as: 'latest_forbidden'
  resources :blocked, only: %i(show), param: :screen_name
  get 'blocked/:screen_name/latest', to: 'blocked#latest', as: 'latest_blocked'
  resources :protected, only: %i(show), param: :screen_name
  get 'protected/:screen_name/latest', to: 'protected#latest', as: 'latest_protected'

  get 'follow', to: 'follows#show'
  resources :follows, only: %i(create)
  resources :unfollows, only: %i(create)
  resources :shares, only: %i(create)

  get 'usage_stats/:uid/check_for_updates', to: 'usage_stats#check_for_updates', as: :check_for_updates_usage_stat

  get 'tokimeki_unfollow', to: 'tokimeki_unfollow#new', as: :tokimeki_unfollow_top
  get 'tokimeki_unfollow/cleanup', to: 'tokimeki_unfollow#cleanup', as: :tokimeki_unfollow_cleanup
  post 'tokimeki_unfollow/unfollow', to: 'tokimeki_unfollow#unfollow', as: :tokimeki_unfollow_unfollow
  post 'tokimeki_unfollow/keep', to: 'tokimeki_unfollow#keep', as: :tokimeki_unfollow_keep

  get 'notifications', to: redirect('/?notifications_not_found=1')
  resources :settings, only: :index
  resource :setting, only: :update
  post 'settings/update_report_interval', to: 'settings#update_report_interval', as: :update_report_interval
  get 'settings/follow_requests', to: "settings#follow_requests"
  get 'settings/unfollow_requests', to: "settings#unfollow_requests"
  get 'settings/create_prompt_requests', to: "settings#create_prompt_report_requests"
  get 'settings/create_test_requests', to: "settings#create_test_report_requests"
  get 'settings/twitter_users', to: "settings#twitter_users"

  namespace :admin do
    get "settings/:user_id/follow_requests", to: "settings#follow_requests"
    get "settings/:user_id/unfollow_requests", to: "settings#unfollow_requests"
    get "settings/:user_id/create_prompt_report_requests", to: "settings#create_prompt_report_requests"
  end

  get 'pricing', to: "pricing#new"
  resources :orders, only: %i(create destroy)
  get 'orders/success', to: "orders#success"
  get 'orders/cancel', to: "orders#cancel"
  post 'orders/checkout_session_completed', to: "orders#checkout_session_completed"

  get 'webhook/twitter', to: 'webhook#challenge'
  post 'webhook/twitter', to: 'webhook#twitter'

  get 'update_histories/:uid', to: redirect('/settings?via=routing_update_histories')

  get 'adsense', to: 'adsense#new'
  get 'search_histories', to: 'search_histories#new'
  get 'load_public_tweets', to: 'public_tweets#load', as: :load_public_tweets

  get 'relationships/:src_uid/:dst_uid/waiting', to: redirect('/')
  get 'relationships/:src_uid/:dst_uid/check_log', to: redirect('/')
  get 'relationships/:src_screen_name/:dst_screen_name', to: redirect('/')

  %i(sign_in after_sign_in after_sign_up goodbye).each do |name|
    get name, to: "login##{name}", as: name
  end
  delete :sign_out, to: "login#sign_out", as: :sign_out
  get 'welcome', to: "welcome#new"

  get 'search_count', to: 'search_count#new'

  devise_for :users, skip: %i(sessions confirmations registrations passwords unlocks), controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    get '_sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
    match 'app_stats' => proc {
      [200, {'Content-Type' => 'text/plain'}, [DirectMessageStats.new.to_s + "\n\n" + RedisStats.new.to_s]]
    }, via: :get
  end

  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
      mount Sidekiq::Web => '/sidekiq'
      mount Blazer::Engine, at: '/blazer' if defined?(Blazer::Engine)
    end
  elsif Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
    mount Blazer::Engine, at: '/blazer'
  end

  match '*unmatched_route', to: 'application#not_found', via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Concerns::JobQueueingConcern

  before_action :require_login!, only: :start

  before_action do
    push_referer

    if session[:sign_in_from].present?
      create_search_log(referer: session.delete(:sign_in_from))
    elsif session[:sign_out_from].present?
      create_search_log(referer: session.delete(:sign_out_from))
    else
      create_search_log
    end
  end

  def new
    enqueue_update_authorized
    set_flash_message
  end

  def start
    if user_signed_in?
      @user = build_twitter_user_by_uid(current_user.uid) # It's possible to be redirected in #build_twitter_user_by_uid
      return if performed?
      @screen_name = @user.screen_name
    else
      # Crawler
      @user = nil
      @screen_name = 'Visitor'
    end
  end

  private

  def after_start_redirect_path
    url = timeline_path(screen_name: current_user.screen_name, via: current_via('auto_redirect_from_start'))
    url = append_query_params(url, follow_dialog: params[:follow_dialog]) if params[:follow_dialog]
    url = append_query_params(url, share_dialog: params[:share_dialog]) if params[:share_dialog]
    url
  end

  def set_flash_message
    via = params[:via].to_s

    if params[:back_from_twitter] == 'true'
      flash.now[:notice] = t('before_sign_in.back_from_twitter_html', url: sign_in_path(via: current_via('back_from_twitter')))

    elsif via.end_with?('secret_mode_detected')
      url = sign_in_path(via: current_via('secret_mode_detected'))
      options = {device_type: request.device_type, os: request.os, os_version: request.os_version, browser: request.browser, browser_version: request.browser_version}
      flash.now[:alert] = t('before_sign_in.secret_mode_detected', options.merge!(url: url))

    elsif via.end_with?('ad_blocker_detected')
      flash.now[:alert] = t('before_sign_in.ad_blocker_detected')

    elsif via.end_with?('unauthorized_detected')
      if user_signed_in?
        url = sign_in_path(via: current_via('signed_in_user_not_authorized'))
        flash.now[:alert] = t('after_sign_in.signed_in_user_not_authorized_html', user: current_user.screen_name, url: url)
      end

    elsif via.end_with?('blocked_detected')
      if user_signed_in?
        url = sign_in_path(via: current_via('egotter_is_blocked'))
        flash.now[:alert] = t('after_sign_in.egotter_is_blocked_html', user: current_user.screen_name)
      end
    end
  end
end

app/views/home/new.html.erb
<%= render partial: 'shared/side_by_side_section', locals: {right_side: {header: t('.right_side.header'), subheader: t('.right_side.subheader'), lead: t('.right_side.lead_html')}} %>
<%= render partial: 'shared/review_section' %>
<%= render partial: 'shared/features_section' %>
<%= render partial: 'shared/functions_section' %>
<%= render partial: 'shared/announcement_section' %>

<% if show_redirection_modal? %>
  <%= render partial: 'modal/redirection_modal', locals: {title: t('.redirection_modal.title', user: current_user.screen_name), body: t('.redirection_modal.body', user: current_user.screen_name), url: timeline_path(current_user)} %>
<% end %>

app/views/home/start.html.haml
- content_for :canonical_url do
  %link{href: start_url(screen_name: @screen_name), rel: 'canonical'}

- page_title = t('.page_title', user: @screen_name)
- title page_title
- set_meta_tags description: t('.meta_description', user: @screen_name)

.container.my-5
  .card.mx-auto{style: 'max-width: 500px;'}
    .text-center.pt-3
      = image_tag '/egotter_welcome_400x448.png', style: 'width: 50%;', class: 'img-rounded'
    .card-body
      %p.card-text
        %div= t('.message1_html')
        %div= t('.message2')
      .text-center
        - url = searches_path(screen_name: @screen_name, via: current_via('start_button'))
        = link_to t('.start_by', user: @screen_name), url, class: 'btn btn-primary', method: :post

.container
  = render(partial: 'adsense/ad', locals: {vertical: :top})

#notification.container.my-5
  .card.mx-auto{style: 'max-width: 500px;'}
    .card-body.pt-3
      %h2.h5.card-title.text-center.mb-3= t('.notification.title')
      .text-center
        = image_tag '/egotter_email_with_text_400x448.png', class: 'img-rounded', height: '160px', style: 'display: block; margin: 0 auto;'
      %p.card-text
        %div= t('.notification.message_html')
      .text-center
        - url = "https://twitter.com/messages/#{current_user.uid}-187385226"
        = link_to t('.notification.button1'), url, target: '_blank', class: 'btn btn-primary mb-3'
        - url = 'https://twitter.com/settings/safety'
        = link_to t('.notification.button2'), url, target: '_blank', class: 'btn btn-outline-primary'

#revive-notification.container.my-5
  .card.mx-auto{style: 'max-width: 500px;'}
    .card-body.pt-3
      %h2.h5.card-title.text-center.mb-3= t('.revive_notification.title')
      .text-center
        = image_tag '/egotter_email_with_text_400x448.png', class: 'img-rounded', height: '160px', style: 'display: block; margin: 0 auto;'
      %p.card-text
        %div= t('.revive_notification.message_html')
        .my-3= t('.revive_notification.step1_html', uid: current_user.uid)
        .my-3= t('.revive_notification.step2_html')
        .my-3= t('.revive_notification.step3_html', user: current_user.screen_name, url: timeline_path(current_user, via: current_via('revive_notification')))
      .text-center
        - url = "https://twitter.com/messages/#{current_user.uid}-187385226?text=リムられ通知 復活"
        = link_to t('.revive_notification.button'), url, target: '_blank', class: 'btn btn-primary'

.container.my-5
  .card.mx-auto{style: 'max-width: 500px;'}
    .card-body.pt-3
      %h2.h5.card-title.text-center.mb-3= t('.question.title')
      .text-center
        = image_tag '/egotter_chat_with_text_400x448.png', class: 'img-rounded', height: '160px', style: 'display: block; margin: 0 auto;'
      %p.card-text
        %div= t('.question.message1_html')
        %div= t('.question.message2_html')
      .text-center
        - url = 'https://twitter.com/ego_tter'
        = link_to t('.question.button'), url, target: '_blank', class: 'btn btn-primary'