config/routes.rb
Rails.application.routes.draw do
  if ENV['MAINTENANCE'] == '1'
    root 'misc#maintenance'
    match '*path' => 'misc#maintenance', via: :all
  else
    root 'home#new'
    get 'start', to: 'home#start', as: 'start'
  end

  namespace :api, {format: 'json'} do
    namespace :v1 do
      Search::API_V1_NAMES.each { |menu| get "#{menu}/summary", to: "#{menu}#summary" }
      Search::API_V1_NAMES.each { |menu| get "#{menu}/list", to: "#{menu}#list" }
      get "summary/summary", to: "summary#summary"

      post 'users/update_instance_id', to: 'users#update_instance_id'
      post 'users/update_device_token', to: 'users#update_device_token'
      post 'periodic_report_settings', to: 'periodic_report_settings#update'
    end
  end

  get 'delete_tweets', to: 'delete_tweets#new'
  get 'delete_tweets/mypage', to: 'delete_tweets#show', as: :delete_tweets_mypage
  post "delete_tweets", to: "delete_tweets#delete"

  delete "reset_egotter", to: "reset_egotter#reset"
  post "reset_cache", to: "reset_cache#reset"

  namespace :directory do
    get "profiles(/:id1(/:id2))", to: "profiles#show", as: :profile
    get "timelines(/:id1(/:id2))", to: "timelines#show", as: :timeline
  end

  %i(maintenance privacy_policy terms_of_service specified_commercial_transactions support).each do |name|
    get name, to: "misc##{name}", as: name
  end
  get '/menu', to: redirect('/settings?via=routing_menu')

  %i(
    profiles
    friends
    followers
    statuses
    audience_insights
    close_friends
    favorite_friends
    scores
    usage_stats
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    resources controller_name, only: %i(show), param: :screen_name
  end

  get 'profiles/:screen_name/latest', to: 'profiles#latest', as: 'latest_profile'

  %i(
    friends
    followers
    close_friends
    favorite_friends
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    get "#{controller_name}/:screen_name/all", to: "#{controller_name}#all", as: "all_#{controller_name}"
  end
  match 'statuses/:screen_name/oembed' => proc { [404, {'Content-Type' => 'text/plain'}, ''] }, via: :get

  get 'one_sided_friends', to: 'one_sided_friends#new', as: :one_sided_friends_top
  get 'unfriends', to: 'unfriends#new', as: :unfriends_top
  get 'inactive_friends', to: 'inactive_friends#new', as: :inactive_friends_top
  get 'friends', to: 'friends#new', as: :friends_top
  get 'conversations', to: redirect('/')
  get 'relationships', to: redirect('/')

  resources :clusters, only: %i(create show), param: :screen_name
  get 'clusters', to: 'clusters#new', as: :clusters_top

  get '/searches/:screen_name/favoriting', to: redirect('/favorite_friends/%{screen_name}')
  %i(
      close_friends
      usage_stats
      inactive_friends
      friends
      followers
      blocking_or_blocked
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu}/%{screen_name}") }
  get '/searches/:screen_name/inactive_followers', to: redirect('/inactive_friends/%{screen_name}')
  %w(
      new_friends
      new_followers
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu.remove('new_')}/%{screen_name}") }
  get '/searches/:screen_name/clusters_belong_to', to: redirect('/clusters/%{screen_name}')

  resources :searches, only: %i(create), param: :screen_name
  get '/searches/:screen_name', to: redirect('/timelines/%{screen_name}')
  get 'searches/:uid/waiting', to: redirect('/waiting/%{uid}')
  get 'waiting/:uid', to: 'waiting#new', as: :waiting

  resources :account_statuses, only: %i(show), param: :uid
  resources :twitter_users, only: %i(create show), param: :uid
  get 'twitter_users/:uid/changes', to: 'twitter_users#changes', as: :twitter_users_changes

  resources :timelines, only: %i(show), param: :screen_name

  resources :not_found, only: %i(show), param: :screen_name
  get 'not_found/:screen_name/latest', to: 'not_found#latest', as: 'latest_not_found'
  resources :forbidden, only: %i(show), param: :screen_name
  get 'forbidden/:screen_name/latest', to: 'forbidden#latest', as: 'latest_forbidden'
  resources :blocked, only: %i(show), param: :screen_name
  get 'blocked/:screen_name/latest', to: 'blocked#latest', as: 'latest_blocked'
  resources :protected, only: %i(show), param: :screen_name
  get 'protected/:screen_name/latest', to: 'protected#latest', as: 'latest_protected'

  get 'follow', to: 'follows#show'
  resources :follows, only: %i(create)
  resources :unfollows, only: %i(create)
  resources :shares, only: %i(create)

  get 'usage_stats/:uid/check_for_updates', to: 'usage_stats#check_for_updates', as: :check_for_updates_usage_stat

  get 'tokimeki_unfollow', to: 'tokimeki_unfollow#new', as: :tokimeki_unfollow_top
  get 'tokimeki_unfollow/cleanup', to: 'tokimeki_unfollow#cleanup', as: :tokimeki_unfollow_cleanup
  post 'tokimeki_unfollow/unfollow', to: 'tokimeki_unfollow#unfollow', as: :tokimeki_unfollow_unfollow
  post 'tokimeki_unfollow/keep', to: 'tokimeki_unfollow#keep', as: :tokimeki_unfollow_keep

  get 'notifications', to: redirect('/?notifications_not_found=1')
  resources :settings, only: :index
  resource :setting, only: :update
  post 'settings/update_report_interval', to: 'settings#update_report_interval', as: :update_report_interval
  get 'settings/follow_requests', to: "settings#follow_requests"
  get 'settings/unfollow_requests', to: "settings#unfollow_requests"
  get 'settings/create_prompt_requests', to: "settings#create_prompt_report_requests"
  get 'settings/create_test_requests', to: "settings#create_test_report_requests"
  get 'settings/twitter_users', to: "settings#twitter_users"

  namespace :admin do
    get "settings/:user_id/follow_requests", to: "settings#follow_requests"
    get "settings/:user_id/unfollow_requests", to: "settings#unfollow_requests"
    get "settings/:user_id/create_prompt_report_requests", to: "settings#create_prompt_report_requests"
  end

  get 'pricing', to: "pricing#new"
  resources :orders, only: %i(create destroy)
  get 'orders/success', to: "orders#success"
  get 'orders/cancel', to: "orders#cancel"
  post 'orders/checkout_session_completed', to: "orders#checkout_session_completed"

  get 'webhook/twitter', to: 'webhook#challenge'
  post 'webhook/twitter', to: 'webhook#twitter'

  get 'update_histories/:uid', to: redirect('/settings?via=routing_update_histories')

  get 'adsense', to: 'adsense#new'
  get 'search_histories', to: 'search_histories#new'
  get 'load_public_tweets', to: 'public_tweets#load', as: :load_public_tweets

  get 'relationships/:src_uid/:dst_uid/waiting', to: redirect('/')
  get 'relationships/:src_uid/:dst_uid/check_log', to: redirect('/')
  get 'relationships/:src_screen_name/:dst_screen_name', to: redirect('/')

  %i(sign_in after_sign_in after_sign_up goodbye).each do |name|
    get name, to: "login##{name}", as: name
  end
  delete :sign_out, to: "login#sign_out", as: :sign_out
  get 'welcome', to: "welcome#new"

  get 'search_count', to: 'search_count#new'

  devise_for :users, skip: %i(sessions confirmations registrations passwords unlocks), controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    get '_sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
    match 'app_stats' => proc {
      [200, {'Content-Type' => 'text/plain'}, [DirectMessageStats.new.to_s + "\n\n" + RedisStats.new.to_s]]
    }, via: :get
  end

  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
      mount Sidekiq::Web => '/sidekiq'
      mount Blazer::Engine, at: '/blazer' if defined?(Blazer::Engine)
    end
  elsif Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
    mount Blazer::Engine, at: '/blazer'
  end

  match '*unmatched_route', to: 'application#not_found', via: :all
end

app/models/concerns/twitter_user/api.rb
require 'active_support/concern'

module Concerns::TwitterUser::Api
  extend ActiveSupport::Concern

  included do
  end

  class_methods do
  end

  def one_sided_friends_rate
    (one_sided_friendships.size.to_f / friend_uids.size) rescue 0.0
  end

  def one_sided_followers_rate
    (one_sided_followerships.size.to_f / follower_uids.size) rescue 0.0
  end

  def follow_back_rate
    numerator = mutual_friendships.size
    denominator = follower_uids.size
    (numerator == 0 || denominator == 0) ? 0.0 : numerator.to_f / denominator
  rescue
    0.0
  end

  def conversations(other)
    statuses1 = status_tweets.select { |status| status.mention_to?(other.mention_name) }
    statuses2 = other.status_tweets.select { |status| status.mention_to?(mention_name) }
    (statuses1 + statuses2).sort_by { |status| -status.tweeted_at.to_i }
  end

  def replying_uids(uniq: true)
    return [] unless usage_stat
    uids = usage_stat.mentions.keys.map(&:to_s).map(&:to_i)
    uniq ? uids.uniq : uids
  end

  def replying(uniq: true)
    uids = replying_uids(uniq: uniq)
    users = TwitterDB::User.where(uid: uids).index_by(&:uid)
    uids.map { |uid| users[uid] }.compact
  end

  def reply_tweets(login_user: nil)
    if login_user&.uid&.to_i == uid.to_i
      mention_tweets
    else
      mention_tweets.select { |status| !status.user&.protected }
    end
  end

  def replied_uids(uniq: true, login_user: nil)
    uids = reply_tweets(login_user: login_user).map { |tweet| tweet.user&.id }.compact
    uniq ? uids.uniq : uids
  end

  def replied(uniq: true, login_user: nil)
    users = reply_tweets(login_user: login_user).map(&:user).compact
    users.uniq!(&:id) if uniq
    users.each { |user| user.uid = user.id }
  end

  def replying_and_replied_uids(uniq: true, login_user: nil)
    replying_uids(uniq: uniq) & replied_uids(uniq: uniq, login_user: login_user)
  end

  def replying_and_replied(uniq: true, login_user: nil)
    uids = replying_and_replied_uids(uniq: uniq, login_user: login_user)
    users = (replying(uniq: uniq) + replied(uniq: uniq, login_user: login_user)).index_by(&:uid)
    uids.map { |uid| users[uid] }.compact
  end
end

app/models/concerns/twitter_user/association_builder.rb
require 'active_support/concern'

module Concerns::TwitterUser::AssociationBuilder
  extend ActiveSupport::Concern
  include Concerns::TwitterUser::Validation

  class_methods do
  end

  included do
  end

  def attach_friend_uids(uids)
    if uids&.any?
      @reserved_friend_uids = uids
      self.friends_size = uids.size
    else
      @reserved_friend_uids = []
      self.friends_size = 0
    end
  end

  def attach_follower_uids(uids)
    if uids&.any?
      @reserved_follower_uids = uids
      self.followers_size = uids.size
    else
      @reserved_follower_uids = []
      self.followers_size = 0
    end
  end

  def attach_user_timeline(tweets)
    if tweets&.any?
      @reserved_statuses = tweets.map { |status| TwitterDB::Status.build_by(twitter_user: self, status: status) }
    else
      @reserved_statuses = []
    end
  end

  def attach_mentions_timeline(tweets, search_result)
    if (tweets.nil? || tweets.empty?) && search_result&.any?
      tweets = reject_self_tweet_and_retweet(search_result)
    end

    if tweets&.any?
      @reserved_mentions = tweets.map { |status| TwitterDB::Mention.build_by(twitter_user: self, status: status) }
    else
      @reserved_mentions = []
    end
  end

  def reject_self_tweet_and_retweet(tweets)
    tweets.reject { |status| uid == status[:user][:id] || status[:text].start_with?("RT @#{screen_name}") }
  end

  def attach_favorite_tweets(tweets)
    if tweets&.any?
      @reserved_favorites = tweets.map { |status| TwitterDB::Favorite.build_by(twitter_user: self, status: status) }
    else
      @reserved_favorites = []
    end
  end
end

app/models/concerns/twitter_user/builder.rb
require 'active_support/concern'

module Concerns::TwitterUser::Builder
  extend ActiveSupport::Concern
  include Concerns::TwitterUser::AssociationBuilder

  class_methods do
    def build_by(user:)
      TwitterUser.new(
          uid: user[:id],
          screen_name: user[:screen_name],
          friends_count: user[:friends_count],
          followers_count: user[:followers_count],
          profile_text: Concerns::TwitterUser::Builder.filter_save_keys(user)
      )
    end
  end

  module_function

  def filter_save_keys(user)
    user.symbolize_keys.slice(*Concerns::TwitterUser::Profile::SAVE_KEYS).to_json
  end
end

app/models/concerns/twitter_user/calculator.rb
require 'active_support/concern'

module Concerns::TwitterUser::Calculator
  extend ActiveSupport::Concern

  included do
  end

  class_methods do
  end

  def calc_uids_for(klass)
    if klass == S3::OneSidedFriendship
      calc_one_sided_friend_uids
    elsif klass == S3::OneSidedFollowership
      calc_one_sided_follower_uids
    elsif klass == S3::MutualFriendship
      calc_mutual_friend_uids
    elsif klass == S3::InactiveFriendship
      calc_inactive_friend_uids
    elsif klass == S3::InactiveFollowership
      calc_inactive_follower_uids
    elsif klass == S3::InactiveMutualFriendship
      calc_inactive_mutual_friend_uids
    else
      raise "#{__method__} Invalid klass is passed klass=#{klass}"
    end
  end

  def calc_one_sided_friend_uids
    friend_uids - follower_uids
  end

  def calc_one_sided_follower_uids
    follower_uids - friend_uids
  end

  def calc_mutual_friend_uids
    friend_uids & follower_uids
  end

  # private
  def calc_favorite_uids
    favorite_tweets.map { |fav| fav&.user&.id }.compact
  end

  # private
  def sort_by_count_desc(ids)
    ids.each_with_object(Hash.new(0)) { |id, memo| memo[id] += 1 }.sort_by { |_, v| -v }.map(&:first)
  end

  def calc_favorite_friend_uids(uniq: true)
    uids = calc_favorite_uids
    uniq ? sort_by_count_desc(uids) : uids
  end

  def calc_close_friend_uids(login_user:)
    uids = replying_uids(uniq: false) + replied_uids(uniq: false, login_user: login_user) + calc_favorite_friend_uids(uniq: false)
    sort_by_count_desc(uids).take(50)
  end

  def calc_inactive_friend_uids
    friends(inactive: true).map(&:uid)
  end

  def calc_inactive_follower_uids
    followers(inactive: true).map(&:uid)
  end

  def calc_inactive_mutual_friend_uids
    mutual_friends(inactive: true).map(&:uid)
  end

  def calc_block_friend_uids
    calc_unfriend_uids & calc_unfollower_uids
  end

  def unfriends_builder
    @unfriends_builder ||= UnfriendsBuilder.new(uid, end_date: created_at)
  end

  def calc_unfriend_uids
    unfriends_builder.unfriends.flatten
  end

  def calc_unfollower_uids
    unfriends_builder.unfollowers.flatten
  end
end

app/models/concerns/twitter_user/dirty.rb
require 'active_support/concern'

module Concerns::TwitterUser::Dirty
  extend ActiveSupport::Concern

  class_methods do
  end

  included do
  end

  # return:
  # {
  #    friends_count:   [111, 222]
  #    followers_count: [333, 444]
  #    friend_uids:     [[1, 2, 3], [3, 4, 5]]
  #    follower_uids:   [[1, 2, 3], [3, 4, 5]]
  #  }
  def diff(newer)
    older = self

    diff = Diff.from_record(older, newer)

    if Rails.env.development?
      logger.debug { "#{self.class}##{__method__} uid=#{uid} screen_name=#{screen_name} diff.keys=#{diff.keys}" }
    end

    diff
  end

  class Diff < Hash
    def initialize(hash)
      hash.each { |key, value| self[key] = value }
    end

    class << self
      def from_record(older, newer)
        array = []

        %i(friends_count followers_count friend_uids follower_uids).map do |attr|
          values = [older.send(attr), newer.send(attr)]
          values = values.map(&:sort) if %i(friend_uids follower_uids).include?(attr)
          array << [attr, values]
        end

        hash = array.to_h
        hash.reject! { |_, v| v[0] == v[1] }

        new(hash)
      end
    end
  end
end

app/models/concerns/twitter_user/inflections.rb
require 'active_support/concern'

module Concerns::TwitterUser::Inflections
  extend ActiveSupport::Concern

  included do
  end

  def mention_name
    @mention_name ||= "@#{screen_name}"
  end
end

app/models/concerns/twitter_user/multiple_people_api.rb
require 'active_support/concern'

module Concerns::TwitterUser::MultiplePeopleApi
  extend ActiveSupport::Concern

  def common_friend_uids(other)
    friend_uids & other.friend_uids
  end

  def common_friends(other)
    friends.select { |f| other.friend_uids.include?(f.uid) }
  end

  def common_follower_uids(other)
    follower_uids & other.follower_uids
  end

  def common_followers(other)
    followers.select { |f| other.follower_uids.include?(f.uid) }
  end

  def common_mutual_friend_uids(other)
    mutual_friend_uids & other.mutual_friend_uids
  end

  def common_mutual_friends(other)
    TwitterDB::User.where_and_order_by_field(uids: common_mutual_friend_uids(other))
  end
end

app/models/concerns/twitter_user/query_methods.rb
require 'active_support/concern'

module Concerns::TwitterUser::QueryMethods
  extend ActiveSupport::Concern

  DEFAULT_TIMESTAMP_DELAY = 3.seconds

  class_methods do
    def latest_by(condition)
      order(created_at: :desc).find_by(condition)
    end

    def with_delay
      where('created_at < ?', DEFAULT_TIMESTAMP_DELAY.ago)
    end
  end

  included do
    scope :creation_completed, -> do
      where.not('friends_size = 0 and followers_size = 0')
    end
  end
end

app/views/twitter_users/_bg_polling.html.haml
- button_classes = 'btn btn-outline-primary'

= alert_info_box('update-this-page-box') do |id, via|
  %span.next-creation-note= next_creation_message(twitter_user)
  = link_to(t('twitter_users.in_background.reload_page'), timeline_path(twitter_user, via: via), class: button_classes)

= alert_info_box('request-to-update-box') do |id, via|
  %span.next-creation-note= ''
  = link_to(t('twitter_users.in_background.request_to_update'), timeline_path(twitter_user, via: via), class: button_classes)

= alert_warning_box('failed-box') do |id, via|
  %span= t('twitter_users.in_background.failed')
  = link_to(t('twitter_users.in_background.reload_page'), timeline_path(twitter_user, via: via), class: button_classes)

= alert_info_box('refresh-box') do |id, via|
  %span.message= t('twitter_users.show.update_is_coming', user: twitter_user.screen_name)
  = link_to(t('twitter_users.in_background.reload_page'), timeline_path(twitter_user, via: via), class: button_classes)

= alert_info_box('too-many-friends-box') do |id, via|
  = t('twitter_users.in_background.too_many_friends', user: twitter_user.screen_name)
  = link_to(t('twitter_users.in_background.do_sign_in'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

- if user_signed_in?
  = alert_warning_box('follow-box') do |id, via|
    - url = sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via), follow: true)
    = t('twitter_users.in_background.automated_update_stopped_html', user: current_user.screen_name, url: url)

= alert_info_box('just-followed-box') do |id, via|
  = t('twitter_users.in_background.automated_update_restarted_html')

= alert_warning_box('not-followed-box') do |id, via|
  - url = sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via), follow: true)
  = t('twitter_users.in_background.automated_update_not_restarted_and_signing_in_html', url: url)

= alert_warning_box('invalid-token-box') do |id, via|
  = t('twitter_users.in_background.invalid_token', user: twitter_user.screen_name)
  = link_to(t('twitter_users.in_background.do_sign_in'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

= alert_warning_box('accurate-counting-box') do |id, via|
  = t('twitter_users.in_background.accurate_counting')
  = link_to(t('twitter_users.in_background.do_sign_in'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

= alert_warning_box('via-dm-box') do |id, via|
  = t('twitter_users.in_background.via_dm')
  = link_to(t('twitter_users.in_background.do_sign_in'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

= alert_info_box('sign-in-box') do |id, via|
  = t('twitter_users.in_background.lets_sign_in')
  = link_to(t('twitter_users.in_background.do_sign_in'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

= alert_info_box('retry-later-box') do |id, via|
  = t('twitter_users.in_background.failed')
  = link_to(t('twitter_users.in_background.retry'), sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via)), class: button_classes)

= alert_info_box('too-many-searches-box') do |id, via|
  - sign_in_url = sign_in_path(via: via, redirect_path: timeline_path(twitter_user, via: via))
  - pricing_url = pricing_path(via: via)
  - support_url = pricing_path(via: via, anchor: 'enterprise-plan')
  = search_count_limitation_too_many_searches_message(sign_in_url, pricing_url, support_url)

= render partial: 'twitter_users/bg_polling_js', locals: {twitter_user: twitter_user}

app/views/twitter_users/_bg_polling_js.html.erb
<%= javascript_pack_tag 'bg_update' %>

<script>
  var signedIn = <%= user_signed_in? %>;
  var crawler = <%= from_crawler? %>;
  var os = '<%= request.os %>';
  var osVersion = '<%= request.os_version %>';
  var removePage = <%= %w(unfriends unfollowers blocking_or_blocked).include?(controller_name) %>;
  var viaDM = <%= via_dm? %>;
  var profileNotFound = <%= twitter_user.profile_not_found? %>;
  var tooShortCreateInterval = <%= twitter_user.too_short_create_interval? %>;
  var accountStatusAccessed = <%= user_signed_in? && AccountStatusAccessFlag.new.accessed?(current_user.id) %>;
  var isEgotterFollower = <%= user_signed_in? && EgotterFollower.exists?(uid: current_user.uid) %>;
  var periodicReportStopped = <%= user_signed_in? && !PeriodicReport.messages_allotted?(current_user) && !StopPeriodicReportRequest.exists?(user_id: current_user.id) %>;
  var eventCategory = '<%= "#{controller_name}/#{action_name}" %>';

  var urls = {
    twitter_users_changes: '<%= twitter_users_changes_path(uid: twitter_user.uid) %>',
    twitter_user: '<%= twitter_user_path(uid: twitter_user.uid, via: current_via('update_box')) %>',
    follow: '<%= follow_path(via: current_via('follow_box')) %>',
    twitter_users: "<%= twitter_users_path(via: current_via('background_update')) %>",
    account_status: "<%= account_status_path(uid: twitter_user.uid) %>"
  };

  var twitterUser = {
    userId: '<%= current_user&.id %>',
    uid: '<%= twitter_user.uid %>',
    screenName: "<%= twitter_user.screen_name %>",
    createdAt: <%= twitter_user.created_at.to_i %>,
    createdAt_s: '<%= twitter_user.created_at %>'
  };

  $(function () {
    if (profileNotFound) {
      ToastMessage.info('<%= t('twitter_users.in_background.profile_not_found_html', url: timeline_path(twitter_user, via: current_via('profile_not_found'))) %>');
      return;
    }

    if (!signedIn) {
      if (removePage) {
        ToastMessage.info($('#accurate-counting-box .inner').html());
      } else if (viaDM) {
        ToastMessage.info($('#via-dm-box .inner').html());
      } else if (!crawler) {
        ToastMessage.info($('#sign-in-box .inner').html());
      } else {
        // Maybe crawler
      }

      return;
    }

    if (signedIn && !isEgotterFollower) {
      ToastMessage.info('<%= t('twitter_users.in_background.is_not_egotter_follower_html', user: current_user&.screen_name, url: sign_in_path(follow: true)) %>');
      return;
    }

    if (signedIn && periodicReportStopped) {
      ToastMessage.info('<%= t('twitter_users.in_background.periodic_report_stopped_html') %>');
      return;
    }

    var options = {url: urls.follow};
    new EgotterFollowerDetector(options).detect(function () {
      if (tooShortCreateInterval) {
        console.warn("Don't start polling since the create interval is too short.", twitterUser);
        ToastMessage.info($('#update-this-page-box .inner').html());
        return;
      }

      var options = {
        url: urls.twitter_users,
        twitterUser: twitterUser
      };
      new CreateTwitterUserRequest(options).perform(function () {

        var options = {
          url: urls.twitter_user,
          changesPath: urls.twitter_users_changes,
          twitterUser: twitterUser
        };
        new Polling(options).start();
        ToastMessage.show('<%= t('twitter_users.in_background.updating_html', user: twitter_user.screen_name) %>');
      });
    });

    if (accountStatusAccessed) {
      console.log('account_status is skipped');
    } else {
      var options = {
        force: true,
        unauthorizedMessage: "<%= t('after_sign_in.unauthorized_detected_with_count', seconds: 3) %>",
        blockedMessage: "<%= t('after_sign_in.blocked_detected_with_count', seconds: 3) %>",
        url: urls.account_status,
        unauthorizedRedirectPath: "<%= root_path(via: current_via('unauthorized_detected')) %>",
        blockedRedirectPath: "<%= root_path(via: current_via('blocked_detected')) %>",
        eventCategory: eventCategory,
        eventLabel: JSON.stringify(twitterUser)
      };
      new UnauthorizedDetector(options).detect();
    }

    if (!crawler) {
      var options = {
        force: true,
        message: '<%= t('before_sign_in.secret_mode_detected_with_count', seconds: 3) %>',
        redirectPath: "<%= root_path(via: current_via('secret_mode_detected')).html_safe %>",
        allowCognite: <%= ENV['ALLOW_COGNITE'] == '1' %>,
        signedIn: signedIn,
        os: os,
        osVersion: osVersion,
        eventCategory: eventCategory,
        eventLabel: JSON.stringify(twitterUser)
      };
      new SecretModeDetector(options).detect();

      var options = {
        force: true,
        message: '<%= t('before_sign_in.ad_blocker_detected_with_count', seconds: 3) %>',
        redirectPath: "<%= root_path(via: current_via('ad_blocker_detected')).html_safe %>",
        eventCategory: eventCategory,
        eventLabel: JSON.stringify(twitterUser)
      };
      new AdBlockDetector(options).detect();
    }
  });
</script>