config/routes.rb
Rails.application.routes.draw do
  if ENV['MAINTENANCE'] == '1'
    root 'misc#maintenance'
    match '*path' => 'misc#maintenance', via: :all
  else
    root 'home#new'
    get 'start', to: 'home#start', as: 'start'
  end

  namespace :api, {format: 'json'} do
    namespace :v1 do
      Search::API_V1_NAMES.each { |menu| get "#{menu}/summary", to: "#{menu}#summary" }
      Search::API_V1_NAMES.each { |menu| get "#{menu}/list", to: "#{menu}#list" }
      get "summary/summary", to: "summary#summary"

      post 'users/update_instance_id', to: 'users#update_instance_id'
      post 'users/update_device_token', to: 'users#update_device_token'
      post 'periodic_report_settings', to: 'periodic_report_settings#update'
    end
  end

  get 'delete_tweets', to: 'delete_tweets#new'
  get 'delete_tweets/mypage', to: 'delete_tweets#show', as: :delete_tweets_mypage
  post "delete_tweets", to: "delete_tweets#delete"

  delete "reset_egotter", to: "reset_egotter#reset"
  post "reset_cache", to: "reset_cache#reset"

  namespace :directory do
    get "profiles(/:id1(/:id2))", to: "profiles#show", as: :profile
    get "timelines(/:id1(/:id2))", to: "timelines#show", as: :timeline
  end

  %i(maintenance privacy_policy terms_of_service specified_commercial_transactions support).each do |name|
    get name, to: "misc##{name}", as: name
  end
  get '/menu', to: redirect('/settings?via=routing_menu')

  %i(
    profiles
    friends
    followers
    statuses
    audience_insights
    close_friends
    favorite_friends
    scores
    usage_stats
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    resources controller_name, only: %i(show), param: :screen_name
  end

  get 'profiles/:screen_name/latest', to: 'profiles#latest', as: 'latest_profile'

  %i(
    friends
    followers
    close_friends
    favorite_friends
    unfriends
    unfollowers
    blocking_or_blocked
    inactive_friends
    inactive_followers
    inactive_mutual_friends
    one_sided_friends
    one_sided_followers
    mutual_friends
    replying
    replied
    replying_and_replied
    common_friends
    common_followers
    common_mutual_friends
  ).each do |controller_name|
    get "#{controller_name}/:screen_name/all", to: "#{controller_name}#all", as: "all_#{controller_name}"
  end
  match 'statuses/:screen_name/oembed' => proc { [404, {'Content-Type' => 'text/plain'}, ''] }, via: :get

  get 'one_sided_friends', to: 'one_sided_friends#new', as: :one_sided_friends_top
  get 'unfriends', to: 'unfriends#new', as: :unfriends_top
  get 'inactive_friends', to: 'inactive_friends#new', as: :inactive_friends_top
  get 'friends', to: 'friends#new', as: :friends_top
  get 'conversations', to: redirect('/')
  get 'relationships', to: redirect('/')

  resources :clusters, only: %i(create show), param: :screen_name
  get 'clusters', to: 'clusters#new', as: :clusters_top

  get '/searches/:screen_name/favoriting', to: redirect('/favorite_friends/%{screen_name}')
  %i(
      close_friends
      usage_stats
      inactive_friends
      friends
      followers
      blocking_or_blocked
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu}/%{screen_name}") }
  get '/searches/:screen_name/inactive_followers', to: redirect('/inactive_friends/%{screen_name}')
  %w(
      new_friends
      new_followers
    ).each { |menu| get "/searches/:screen_name/#{menu}", to: redirect("/#{menu.remove('new_')}/%{screen_name}") }
  get '/searches/:screen_name/clusters_belong_to', to: redirect('/clusters/%{screen_name}')

  resources :searches, only: %i(create), param: :screen_name
  get '/searches/:screen_name', to: redirect('/timelines/%{screen_name}')
  get 'searches/:uid/waiting', to: redirect('/waiting/%{uid}')
  get 'waiting/:uid', to: 'waiting#new', as: :waiting

  resources :account_statuses, only: %i(show), param: :uid
  resources :twitter_users, only: %i(create show), param: :uid
  get 'twitter_users/:uid/changes', to: 'twitter_users#changes', as: :twitter_users_changes

  resources :timelines, only: %i(show), param: :screen_name

  resources :not_found, only: %i(show), param: :screen_name
  get 'not_found/:screen_name/latest', to: 'not_found#latest', as: 'latest_not_found'
  resources :forbidden, only: %i(show), param: :screen_name
  get 'forbidden/:screen_name/latest', to: 'forbidden#latest', as: 'latest_forbidden'
  resources :blocked, only: %i(show), param: :screen_name
  get 'blocked/:screen_name/latest', to: 'blocked#latest', as: 'latest_blocked'
  resources :protected, only: %i(show), param: :screen_name
  get 'protected/:screen_name/latest', to: 'protected#latest', as: 'latest_protected'

  get 'follow', to: 'follows#show'
  resources :follows, only: %i(create)
  resources :unfollows, only: %i(create)
  resources :shares, only: %i(create)

  get 'usage_stats/:uid/check_for_updates', to: 'usage_stats#check_for_updates', as: :check_for_updates_usage_stat

  get 'tokimeki_unfollow', to: 'tokimeki_unfollow#new', as: :tokimeki_unfollow_top
  get 'tokimeki_unfollow/cleanup', to: 'tokimeki_unfollow#cleanup', as: :tokimeki_unfollow_cleanup
  post 'tokimeki_unfollow/unfollow', to: 'tokimeki_unfollow#unfollow', as: :tokimeki_unfollow_unfollow
  post 'tokimeki_unfollow/keep', to: 'tokimeki_unfollow#keep', as: :tokimeki_unfollow_keep

  get 'notifications', to: redirect('/?notifications_not_found=1')
  resources :settings, only: :index
  resource :setting, only: :update
  post 'settings/update_report_interval', to: 'settings#update_report_interval', as: :update_report_interval
  get 'settings/follow_requests', to: "settings#follow_requests"
  get 'settings/unfollow_requests', to: "settings#unfollow_requests"
  get 'settings/create_prompt_requests', to: "settings#create_prompt_report_requests"
  get 'settings/create_test_requests', to: "settings#create_test_report_requests"
  get 'settings/twitter_users', to: "settings#twitter_users"

  namespace :admin do
    get "settings/:user_id/follow_requests", to: "settings#follow_requests"
    get "settings/:user_id/unfollow_requests", to: "settings#unfollow_requests"
    get "settings/:user_id/create_prompt_report_requests", to: "settings#create_prompt_report_requests"
  end

  get 'pricing', to: "pricing#new"
  resources :orders, only: %i(create destroy)
  get 'orders/success', to: "orders#success"
  get 'orders/cancel', to: "orders#cancel"
  post 'orders/checkout_session_completed', to: "orders#checkout_session_completed"

  get 'webhook/twitter', to: 'webhook#challenge'
  post 'webhook/twitter', to: 'webhook#twitter'

  get 'update_histories/:uid', to: redirect('/settings?via=routing_update_histories')

  get 'adsense', to: 'adsense#new'
  get 'search_histories', to: 'search_histories#new'
  get 'load_public_tweets', to: 'public_tweets#load', as: :load_public_tweets

  get 'relationships/:src_uid/:dst_uid/waiting', to: redirect('/')
  get 'relationships/:src_uid/:dst_uid/check_log', to: redirect('/')
  get 'relationships/:src_screen_name/:dst_screen_name', to: redirect('/')

  %i(sign_in after_sign_in after_sign_up goodbye).each do |name|
    get name, to: "login##{name}", as: name
  end
  delete :sign_out, to: "login#sign_out", as: :sign_out
  get 'welcome', to: "welcome#new"

  get 'search_count', to: 'search_count#new'

  devise_for :users, skip: %i(sessions confirmations registrations passwords unlocks), controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    get '_sign_out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
    match 'app_stats' => proc {
      [200, {'Content-Type' => 'text/plain'}, [DirectMessageStats.new.to_s + "\n\n" + RedisStats.new.to_s]]
    }, via: :get
  end

  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :user, lambda { |u| [User::ADMIN_UID, User::EGOTTER_UID].include?(u.uid) } do
      mount Sidekiq::Web => '/sidekiq'
      mount Blazer::Engine, at: '/blazer' if defined?(Blazer::Engine)
    end
  elsif Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
    mount Blazer::Engine, at: '/blazer'
  end

  match '*unmatched_route', to: 'application#not_found', via: :all
end

app/controllers/tokimeki_unfollow_controller.rb
class TokimekiUnfollowController < ApplicationController
  include Concerns::SearchRequestConcern
  include Concerns::UnfriendsConcern

  before_action :require_login!, only: %i(cleanup unfollow keep)

  rescue_from Exception do |ex|
    if AccountStatus.unauthorized?(ex)
      redirect_to tokimeki_unfollow_top_path(via: current_via('unauthorized')), alert: signed_in_user_not_authorized_message
    else
      logger.warn "#{controller_name}##{action_name} #{current_user_id} #{ex.inspect}"
      redirect_to tokimeki_unfollow_top_path(via: current_via('something_error')), alert: unknown_alert_message(ex)
    end
  end

  before_action only: :cleanup do
    if current_twitter_user[:friends_count] >= 10000
      redirect_to root_path(via: current_via), alert: t('after_sign_in.tokimeki_unfollow_too_many_friends')
    else
      initialize_data!
      if current_tokimeki_user.processed_count >= current_tokimeki_user.friendships.size
        redirect_to root_path(via: current_via), notice: t('tokimeki_unfollow.cleanup.finish')
      end
    end
  end

  before_action do
    push_referer
    create_search_log
  end

  def new
  end

  def cleanup
    @user = current_tokimeki_user
    begin
      @friend = Friend.new(current_friend(@user))
      @statuses = current_tweets(@friend.uid)
    rescue => e
      status = AccountStatus.new(ex: e)
      if status.not_found? || status.suspended? || status.blocked? || status.protected?
        @user.increment(:processed_count).save!
        retry
      else
        raise
      end
    end

    @twitter_user = TwitterUser.latest_by(uid: @friend.uid)
    @twitter_user = TwitterUser.build_by(user: @friend.user) unless @twitter_user
  end

  def unfollow
    ActiveRecord::Base.transaction do
      current_tokimeki_user.increment(:processed_count).save!
      Tokimeki::Unfriendship.create!(
          user_uid: current_user.uid,
          friend_uid: params[:uid],
          sequence: Tokimeki::Unfriendship.where(user_uid: current_user.uid).size
      )
    end
    head :ok
  end

  def keep
    current_tokimeki_user.increment(:processed_count).save!
    head :ok
  end

  private

  class Friend
    attr_reader :user

    def initialize(user)
      @user = user
    end

    def uid
      @user[:id]
    end

    def screen_name
      @user[:screen_name]
    end
  end

  def current_tokimeki_user
    @current_tokimeki_user ||= Tokimeki::User.find_by(uid: current_user.uid)
  end

  def current_friend(user)
    friend_uids ||= user.friendships.pluck(:friend_uid)

    uid = friend_uids[user.processed_count]
    request_context_client.user(uid)

  rescue => e
    status = AccountStatus.new(ex: e)
    if status.not_found? || status.suspended? || status.blocked? || status.protected?
      user.increment(:processed_count).save!
      retry
    else
      raise
    end
  end

  def current_tweets(uid)
    request_context_client.user_timeline(uid, count: 100).reject do |tweet|
      tweet[:text].to_s.starts_with?('@')
    end.take(20).map { |t| Hashie::Mash.new(t) }
  end

  def current_twitter_user
    request_context_client.user(current_user.uid)
  end

  # TODO Reset function
  def initialize_data!
    return if current_tokimeki_user

    user = current_twitter_user
    friend_uids = request_context_client.friend_ids(user[:id])

    friend_uids.each_slice(100) do |uids|
      CreateTwitterDBUserWorker.perform_async(CreateTwitterDBUserWorker.compress(uids), user_id: current_user.id, compressed: true, enqueued_by: 'tokimeki unfollow')
    end

    ActiveRecord::Base.transaction do
      Tokimeki::User.create!(uid: user[:id], screen_name: user[:screen_name], friends_count: user[:friends_count], processed_count: 0)
      Tokimeki::Friendship.import_from!(current_user.uid, friend_uids)
    end
  end
end

app/helpers/tokimeki_unfollow_helper.rb
module TokimekiUnfollowHelper
  LIST = [
      '今はもうときめかなくなったフォローを解除する。それは、新たな門出ともいえる儀式なのです。ぜひその門出を祝福してあげてください',
      '誰をフォローするのかは、まさにどう生きるのかと同じこと',
      '"アンフォロー"とは過去に片をつけること',
      '自分が本当に好きなフォローの根っこは、時がたっても変わらない　その根っこを見つけるのにアンフォローは大いに役立つ',
      '自分がときめくフォローを選び抜く作業を通じて初めて、自分が何を好きで何を求めているのか、はっきりと感じ取ることができる。',
      '今、自分にとって必要なフォローをはっきりさせるためにすることは、不必要なフォローを解除すること',
      'タイムラインは自分の選択の歴史を正確に語ってくれる',
      '大事なのは、どのツイートを残すか　どのツイートと一緒に生活を送っていくと　自分の人生はときめくのか、という感覚で選ぶこと',
      '「捨てる」ことだけを考えてアンフォローをすると不幸になる。アンフォローで選ぶべきなのは、「捨てるフォロー」ではなくて「残すフォロー」'
  ]

  def tokimeki_list
    LIST
  end
end

app/views/tokimeki_unfollow/cleanup.html.haml
- title t('.plain_title')
- set_meta_tags description: t('.description')

.text-center.my-5= t('.next_is_html', number: @user.processed_count + 1, screen_name: @friend.screen_name)

.alert.alert-warning.my-5
  = t('.text001_html', screen_name: @friend.screen_name)
  .mt-3
    %a.btn.btn-warning.unfollow{href: '#', data: {uid: @friend.uid, url: unfollows_path(via: current_via)}}= t('.unfollow')
    %a.btn.btn-warning.keep{href: '#'}= t('.keep')

.my-5= render partial: 'twitter/profile', locals: {user: @twitter_user}

.twitter.tweets= render(partial: 'twitter/tweet', collection: @statuses, cached: true, formats: %i(html))

.text-center.my-5= t('.how_to_continue_html', url: tokimeki_unfollow_top_path)

#after-unfollow-modal.modal.fade{role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-body
        %p= t('.after_unfollow_html', screen_name: @friend.screen_name, remaining: @user.friends_count - (@user.processed_count + 1))
      .modal-footer
        = link_to t('.after_unfollow_modal.next'), tokimeki_unfollow_cleanup_path, class: 'btn btn-primary'

#after-keep-modal.modal.fade{role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-body
        %p= t('.after_keep_html', screen_name: @friend.screen_name, remaining: @user.friends_count - (@user.processed_count + 1))
      .modal-footer
        = link_to t('.after_keep_modal.next'), tokimeki_unfollow_cleanup_path, class: 'btn btn-primary'

:javascript
  $(function () {
    $('.btn.unfollow').on('click', function () {
      var $clicked = $(this);
      var $modal = $('#after-unfollow-modal').one('hidden.bs.modal', function (e) {
        window.location.href = $(this).find('.btn').attr('href');
      });

      new Twitter().unfollow($clicked.data('uid'));
      $.post('#{tokimeki_unfollow_unfollow_path}', {uid: $clicked.data('uid')});
      $modal.modal();
    });

    $('.btn.keep').on('click', function () {
      var $modal = $('#after-keep-modal').one('hidden.bs.modal', function (e) {
        window.location.href = $(this).find('.btn').attr('href');
      });
      $.post('#{tokimeki_unfollow_keep_path}');
      $modal.modal();
    });
  });

app/views/tokimeki_unfollow/new.html.haml
- title t('.plain_title')
- set_meta_tags description: t('.description')
- set_meta_tags og: {image: 'https://egotter.com/egotter_tokimeki_icon_840x450.png'}

= render partial: 'shared/side_by_side_section', locals: {right_side: {header: t('.right_side.header'), subheader: t('.right_side.subheader'), lead: t('.right_side.lead_html')}}

- if show_redirection_modal?
  = render partial: 'modal/redirection_modal', locals: {title: t('.redirection_modal.title', user: current_user.screen_name), body: t('.redirection_modal.body', user: current_user.screen_name), url: tokimeki_unfollow_cleanup_path}

%h2.h4.text-center.my-5= t('.simple_title')

.container
  .my-5= t('.text002_html')
  .my-5= t('.text003_html')

.tokimeki_unfollow
  .block-center
    %blockquote
      %p.lead= tokimeki_list.sample

= render partial: 'shared/review_section'
= render partial: 'shared/features_section'
= render partial: 'shared/functions_section'
= render partial: 'shared/announcement_section'